export const CARD_DATA = [
  {
    Image: "/assets/cpu.webp",
    Heading: "Vortex Gaming PC",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$249.99",
    Btn: "Shop Now",
    category: "Gaming",
  },

  {
    Image: "/assets/wifi.webp",
    Heading: " Router DSL2790U",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$2240.99",
    Btn: "Shop Now",
    category: "Accessories",
  },
  {
    Image: "/assets/gamingchair.webp",
    Heading: "Gaming Chair",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$349.99",
    Btn: "Shop Now",
    category: "Gaming",
  },
  {
    Image: "/assets/mainmemory.webp",
    Heading: "Sensors & Modules",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$239.99",
    Btn: "Shop Now",
    category: "Accessories",
  },
  {
    Image: "/assets/toolbox.webp",
    Heading: "DIY Tools",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$449.99",
    Btn: "Shop Now",
    category: "Tools",
  },
  {
    Image: "/assets/wire.webp",
    Heading: "Cables & Connectors",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$299.99",
    Btn: "Shop Now",
    category: "Accessories",
  },
  {
    Image: "/assets/gameremot.webp",
    Heading: "Gaming Peripherals",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$2249.99",
    Btn: "Shop Now",
    category: "Gaming",
  },
  {
    Image: "/assets/mininas.webp",
    Heading: " Mini NAS",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$2149.99",
    Btn: "Shop Now",
    category: "Accessories",
  },
  {
    Image: "/assets/motherbord.png",
    Heading: "Custom PC Parts",
    Para: "Commodo egestas etiam arcu curabitur aliquam volutpat a gravida.",
    Price: "$349.99",
    Btn: "Shop Now",
    category: "Tools",
  },
];
